### ISSUE TITLE
No active link to the block within the breadcrumb

### ISSUE THREAD

**Issue by Kathrin84** [lsuits/block_quickmail#177]
There's no active link to the plugin within the breadcrumb. Could this be added?
![link](https://cloud.githubusercontent.com/assets/4711883/7040695/2cac19ae-ddd2-11e4-94ff-97810f2b6069.png)

**Comment by rrusso** [comment]
Where would you have that link go?

I'm the screenshot you posted, Quickmail is in the front page course context. A Quickmail link would go to the same page you were on, essentially refreshing the page. 

If you were in a course, it would only serve to refresh the page as well.

What is the desired outcome of a breadcrumb link?

**Comment by Kathrin84** [comment]
Okay, if it would only lead to a refresh of the page, then I've had a wrong idea in my head.
You can close or delete this issue.

**Comment by elliott2081** [comment]
I think there could be a link to the main message part in signatures, and settings(?), and alternate emails, like there is on the log page. The breadcrumb link will stay the same though since as Robert pointed out, since it's a block it doesn't really have a page to go to other than just the course page.
