### ISSUE TITLE
Installing the plugin produces error message when running upgrade.

### ISSUE THREAD

**Issue by colin-umn** [lsuits/block_quickmail#198]
This is the error message that admin/cli/upgrade.php produces when after adding this plugin to the code (in Moodle 3.0).

PHP Notice:  Capability "block/quickmail:myaddinstance" was not found! This has to be fixed in code.
* line 387 of /lib/accesslib.php: call to debugging()
* line 14 of /blocks/quickmail/block_quickmail.php: call to has_capability()
* line 323 of /blocks/moodleblock.class.php: call to block_quickmail->applicable_formats()
* line 838 of /lib/upgradelib.php: call to block_base->_self_test()
* line 429 of /lib/upgradelib.php: call to upgrade_plugins_blocks()
* line 1641 of /lib/upgradelib.php: call to upgrade_plugins()
* line 171 of /admin/cli/upgrade.php: call to upgrade_noncore()

**Comment by rrusso** [comment]
I've not been able to reproduce this notice. You can see that the access.php file has the correct block/quickmail:myaddinstance capability. Let me know if your download differs from this.

$capabilities = array(
    'block/quickmail:myaddinstance' => array(
        'riskbitmask' => RISK_SPAM,
        'captype' => 'write',
        'contextlevel' => CONTEXT_SYSTEM,
        'archetypes' => array(
            'manager' => CAP_ALLOW,
            'frontpage' => CAP_PREVENT,
            'user' => CAP_PREVENT
        )
    ),

    'block/quickmail:addinstance' => array(
        'riskbitmask' => RISK_SPAM,
        'captype' => 'write',
        'contextlevel' => CONTEXT_BLOCK,
        'archetypes' => array(
            'manager' => CAP_ALLOW,
            'editingteacher' => CAP_ALLOW,
            'coursecreator' => CAP_ALLOW
        ),
        'clonepermissionsfrom' => 'moodle/site:manage blocks'

more code cut

**Comment by colin-umn** [comment]
Hi Robert - I tried the fresh code that you just uploaded to the Moodle plugin page.  I can reproduce the error just by installing the Quickmail block.

Were you trying to reproduce the error using admin/cli/ugrade.php?  The cause of the error seems straightforward.  During the execution of admin/cli/upgrade.php, the applicable_formats function calls has_capability for a capability that does not get added until later in the installation process.

Perhaps you do not need that capability check at all.  The user_can_addto function in blocks/moodleblock.class.php checks the myaddinstance capability, anyway.

**Comment by rrusso** [comment]
Do you have the block installed on your /my page?

There’s no call to has_capability in upgrade.php. The block_quickmail.php file calls the capability in question, but that needs to be called in order to prevent regular users form adding the page to Moodle’s /my page.

It looks like the CLI upgrade.php balks about having the has_cap requirement in block_quickmail. It doesn’t fail, merely gives a notice and then finishes properly.

I can see no way to fix this issue as we have to let some people add to the my page and others not add to the my page based on their capability.


On Dec 2, 2015, at 2:21 PM, colin-umn <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Robert - I tried the fresh code that you just uploaded to the Moodle plugin page. I can reproduce the error just by installing the Quickmail block.

Were you trying to reproduce the error using admin/cli/ugrade.php? The cause of the error seems straightforward. During the execution of admin/cli/upgrade.php, the applicable_formats function calls has_capability for a capability that does not get added until later in the installation process.

Perhaps you do not need that capability check at all. The user_can_addto function in blocks/moodleblock.class.php checks the myaddinstance capability, anyway.

**Comment by colin-umn** [comment]
As far as I can tell, it's redundant to have the myaddinstance capability and then also use the myaddinstance to set the applicable_format in applicable_formats (in block_quickmail.php).  Is there some gap in the capability framework that you are trying to compensate for with this double layer of protection?  The user_can_addto function in blocks/moodleblock.class.php might be worth looking at.

And, yes, we could survive with this defect, but I would really like to minimize the errors that pop up as we perform routine operations.  I have not seen any other plugins with this particular issue, and I don't think that Quickmail requirements are especially unique in this area.

**Comment by rrusso** [comment]
Yes. We want those who have the capability to be able to add the block on their /my page as well as on the site home, but also disallow those who do not have the capability from adding it to their site home page.

Merely relying on the applicable formats will still allow the block to be added to the site home or not but not based on role or capability.


On Dec 2, 2015, at 3:13 PM, colin-umn <notifications@github.com<mailto:notifications@github.com>> wrote:


As far as I can tell, it's redundant to have the myaddinstance capability and then also use the myaddinstance to set the applicable_format in applicable_formats (in block_quickmail.php). Is there some gap in the capability framework that you are trying to compensate for with this double layer of protection? The user_can_addto function in blocks/moodleblock.class.php might be worth looking at.

And, yes, we could survive with this defect, but I would really like to minimize the errors that pop up as we perform routine operations. I have not seen any other plugins with this particular issue, and I don't think that Quickmail requirements are especially unique in this area.
