### ISSUE TITLE
Quickmail strips links out of emails

### ISSUE THREAD

**Issue by markchaneyuk** [lsuits/block_quickmail#212]
Moodle 3.0.3, Quickmail version 2015122912, installed on Linux. When an email is sent that contains links, e.g. to YouTube, the links are stripped out of it. No text, or links are sent in the email to the original person or the original sender. 

The following email was inputted: <p>THis is a test <a href="https://www.youtube.com/playlist?list=PLA17C1952AEFB6F41">YouTube Channel</a> AND <a href="https://www.youtube.com/watch?v=BgwHQCaqJc8&amp;feature=youtu.be&amp;list=PLA17C1952AEFB6F41">Choosing a College</a>
  <br>
</p>

The email received was: 
THis is a test AND 

No links.

**Comment by markchaneyuk** [comment]
As an update: This occurs no matter the email provider that is receiving the email, e.g. Outlook, Gmail etc.

**Comment by elliott2081** [comment]
I believe we fixed this, in the Dev-30 branch.

**Comment by elliott2081** [comment]
looks like it hasn't been committed yet. should be up tomorrow. 
thanks for pointing it out.

**Comment by weixish** [comment]
Sorry to bring up an old thread, but I'm curious what fixed this issue. We just had this issue come up with a client. I'm not seeing a difference between the version we're using with this client and the dev-30 branch on this repo. Looking at the code, it looks like it may be related to the use of the format_text function and media filter settings with the core_media_enable_youtube setting turned on. Perhaps this is a different issue. It seems like the media filter probably needs to be bypassed here since it is injecting iframes in the email content. I've verified that the original message in gmail does include iframes when a youtube link is present.

**Comment by rrusso** [comment]
That's exactly it. The filters were trying to inject an iframe into emails and breaking for end users.

**Comment by weixish** [comment]
Thanks for the quick response! Was that fixed then? As far as I can tell the format_text call that sends the text through all filters is still being made when generating the message. Line 303 of email.php is what I'm looking at.

**Comment by rrusso** [comment]
I thought we had fixed that months ago. We had problems with that locally as well.

I'll check it out again when I have some time.
