### ISSUE TITLE
Planned updates?

### ISSUE THREAD

**Issue by jmj5g** [lsuits/block_quickmail#225]
Are there plans to update Quickmail to be compatible with Moodle 3.1 or 3.2? If so, what is the tentative schedule? Moodle central is now only doing security patches to Moodle 3.0.

**Comment by NMCPaul** [comment]
Seconding this question.  We use this plugin extensively and haven't found anything that really comes close to its functionality.

**Comment by lucaboesch** [comment]
It would be as simple as to accept either the
https://github.com/lsuits/block_quickmail/pull/226
or the
https://github.com/lsuits/block_quickmail/pull/216
pull request…

**Comment by rrusso** [comment]
the dev-30 branch has the required changes for Moodle 3.1 and should be good for 3.2. If it's not let us know. The plugin is being maintained by @chadmazilly here at LSU and will be updated far more frequently from now on.

**Comment by abias** [comment]
Hi @rrusso, hi @chadmazilly,

I'd like to chime in here, even if the ticket is already closed.

At Ulm University, we have been happily using this plugin since it was updated by your institution for Moodle 2.x. We are grateful for your work and first of all, I would like to thank you for that.

However, for the last 1.5 years, I got the impression that the work on this plugin has stagnated. Mainly, I don’t see any updates in the Moodle plugin repository on https://moodle.org/plugins/pluginversions.php?plugin=block_quickmail anymore. There, the last version is of winter 2015 which is a sign to me that no-one is fully working on it anymore or at least that the developers don’t care about the community anymore. There are and have been several tickets like this one here in Github which requested an upgrade in the repo, but nothing has happened.

Furthermore, there is a long list of open issues here in Github and also several pull requests fixing fundamental problems and the development of these issues respectively the integration of the pull requests seems no to happen. This is totally disappointing for us and keeping us from contributing anything more to this plugin.

I am fully aware that you can’t process all of the community’s issues immediately and that even looking at the incoming issues is sometimes impossible during the daily work. But you have built and published a plugin which is used on 3000+ sites (according to the official Moodle plugin stats) and the community simply does not get any information about the future of this plugin including the official status of current Moodle versions support (3.1 / 3.2 / 3.3) except some rare and short-spoken answers in Github tickets. I even mailed directly to Buddy Ethridge who is listed as official maintainer in the Moodle plugin repo about this issue twice last year, but did not get _any_ response.

At our university, we are tired of waiting for any sign of life from this plugin anymore and will be moving away from it shortly. I know of other institutions considering the same move.

Just my two cents....
Alex

**Comment by NMCPaul** [comment]
@abias - have you found a plugin with similar functionality?  I've been looking for a bit but not really found anything.  Seeing as how you're looking to move away from Quickmail, I'm hoping you've had more luck than I have.

**Comment by abias** [comment]
@NMCPaul - thanks for asking. No, I haven't found a real alternative to Quickmail yet. That's why I am so disappointed that the developers don't really care about the community anymore.

Currently, we are still on Moodle 3.0 where Quickmail still works basically fine. Soon we will be jumping to 3.2 / 3.3 and we are in doubt if it will still work there.

Our users basically love two main features of quickmail: Sending messages to groups easily and adding attachments to messages. If we drop Quickmail, this won't be possible anymore easily, but the world will keep on turning.

Moodle HQ has announced that they probably will merge the participants page and the enrolled user page in Moodle 3.4 and messaging participants will hopefully be revamped then. At least we have created and spotted some tickets in the Moodle tracker asking for features which currently are provided by quickmail. 
Additionally, you probably know that Moodle HQ wants to get rid of blocks completely and has made a big step into this direction in the Boost theme already - so we would have to think about the discouraged usage of blocks with course management features like quickmail anyway.

Thanks,
Alex
